// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hurra_agent.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RunContainerRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Image                string   `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	PortMappingSource    uint32   `protobuf:"varint,3,opt,name=port_mapping_source,json=portMappingSource,proto3" json:"port_mapping_source,omitempty"`
	PortMappingTarget    uint32   `protobuf:"varint,4,opt,name=port_mapping_target,json=portMappingTarget,proto3" json:"port_mapping_target,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RunContainerRequest) Reset()         { *m = RunContainerRequest{} }
func (m *RunContainerRequest) String() string { return proto.CompactTextString(m) }
func (*RunContainerRequest) ProtoMessage()    {}
func (*RunContainerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1a676bd7648f983, []int{0}
}

func (m *RunContainerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunContainerRequest.Unmarshal(m, b)
}
func (m *RunContainerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunContainerRequest.Marshal(b, m, deterministic)
}
func (m *RunContainerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunContainerRequest.Merge(m, src)
}
func (m *RunContainerRequest) XXX_Size() int {
	return xxx_messageInfo_RunContainerRequest.Size(m)
}
func (m *RunContainerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RunContainerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RunContainerRequest proto.InternalMessageInfo

func (m *RunContainerRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RunContainerRequest) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *RunContainerRequest) GetPortMappingSource() uint32 {
	if m != nil {
		return m.PortMappingSource
	}
	return 0
}

func (m *RunContainerRequest) GetPortMappingTarget() uint32 {
	if m != nil {
		return m.PortMappingTarget
	}
	return 0
}

type RunContainerResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RunContainerResponse) Reset()         { *m = RunContainerResponse{} }
func (m *RunContainerResponse) String() string { return proto.CompactTextString(m) }
func (*RunContainerResponse) ProtoMessage()    {}
func (*RunContainerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1a676bd7648f983, []int{1}
}

func (m *RunContainerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunContainerResponse.Unmarshal(m, b)
}
func (m *RunContainerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunContainerResponse.Marshal(b, m, deterministic)
}
func (m *RunContainerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunContainerResponse.Merge(m, src)
}
func (m *RunContainerResponse) XXX_Size() int {
	return xxx_messageInfo_RunContainerResponse.Size(m)
}
func (m *RunContainerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RunContainerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RunContainerResponse proto.InternalMessageInfo

type KillContainerRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KillContainerRequest) Reset()         { *m = KillContainerRequest{} }
func (m *KillContainerRequest) String() string { return proto.CompactTextString(m) }
func (*KillContainerRequest) ProtoMessage()    {}
func (*KillContainerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1a676bd7648f983, []int{2}
}

func (m *KillContainerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KillContainerRequest.Unmarshal(m, b)
}
func (m *KillContainerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KillContainerRequest.Marshal(b, m, deterministic)
}
func (m *KillContainerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KillContainerRequest.Merge(m, src)
}
func (m *KillContainerRequest) XXX_Size() int {
	return xxx_messageInfo_KillContainerRequest.Size(m)
}
func (m *KillContainerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_KillContainerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_KillContainerRequest proto.InternalMessageInfo

func (m *KillContainerRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type KillContainerResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KillContainerResponse) Reset()         { *m = KillContainerResponse{} }
func (m *KillContainerResponse) String() string { return proto.CompactTextString(m) }
func (*KillContainerResponse) ProtoMessage()    {}
func (*KillContainerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1a676bd7648f983, []int{3}
}

func (m *KillContainerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KillContainerResponse.Unmarshal(m, b)
}
func (m *KillContainerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KillContainerResponse.Marshal(b, m, deterministic)
}
func (m *KillContainerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KillContainerResponse.Merge(m, src)
}
func (m *KillContainerResponse) XXX_Size() int {
	return xxx_messageInfo_KillContainerResponse.Size(m)
}
func (m *KillContainerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_KillContainerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_KillContainerResponse proto.InternalMessageInfo

type ContainerSpecRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Context              string   `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	Spec                 string   `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContainerSpecRequest) Reset()         { *m = ContainerSpecRequest{} }
func (m *ContainerSpecRequest) String() string { return proto.CompactTextString(m) }
func (*ContainerSpecRequest) ProtoMessage()    {}
func (*ContainerSpecRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1a676bd7648f983, []int{4}
}

func (m *ContainerSpecRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContainerSpecRequest.Unmarshal(m, b)
}
func (m *ContainerSpecRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContainerSpecRequest.Marshal(b, m, deterministic)
}
func (m *ContainerSpecRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContainerSpecRequest.Merge(m, src)
}
func (m *ContainerSpecRequest) XXX_Size() int {
	return xxx_messageInfo_ContainerSpecRequest.Size(m)
}
func (m *ContainerSpecRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ContainerSpecRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ContainerSpecRequest proto.InternalMessageInfo

func (m *ContainerSpecRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ContainerSpecRequest) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}

func (m *ContainerSpecRequest) GetSpec() string {
	if m != nil {
		return m.Spec
	}
	return ""
}

type ContainerSpecResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContainerSpecResponse) Reset()         { *m = ContainerSpecResponse{} }
func (m *ContainerSpecResponse) String() string { return proto.CompactTextString(m) }
func (*ContainerSpecResponse) ProtoMessage()    {}
func (*ContainerSpecResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1a676bd7648f983, []int{5}
}

func (m *ContainerSpecResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContainerSpecResponse.Unmarshal(m, b)
}
func (m *ContainerSpecResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContainerSpecResponse.Marshal(b, m, deterministic)
}
func (m *ContainerSpecResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContainerSpecResponse.Merge(m, src)
}
func (m *ContainerSpecResponse) XXX_Size() int {
	return xxx_messageInfo_ContainerSpecResponse.Size(m)
}
func (m *ContainerSpecResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ContainerSpecResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ContainerSpecResponse proto.InternalMessageInfo

type ExecInContainerSpecRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Context              string   `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	Spec                 string   `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"`
	ContainerName        string   `protobuf:"bytes,4,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	Cmd                  string   `protobuf:"bytes,5,opt,name=cmd,proto3" json:"cmd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecInContainerSpecRequest) Reset()         { *m = ExecInContainerSpecRequest{} }
func (m *ExecInContainerSpecRequest) String() string { return proto.CompactTextString(m) }
func (*ExecInContainerSpecRequest) ProtoMessage()    {}
func (*ExecInContainerSpecRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1a676bd7648f983, []int{6}
}

func (m *ExecInContainerSpecRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecInContainerSpecRequest.Unmarshal(m, b)
}
func (m *ExecInContainerSpecRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecInContainerSpecRequest.Marshal(b, m, deterministic)
}
func (m *ExecInContainerSpecRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecInContainerSpecRequest.Merge(m, src)
}
func (m *ExecInContainerSpecRequest) XXX_Size() int {
	return xxx_messageInfo_ExecInContainerSpecRequest.Size(m)
}
func (m *ExecInContainerSpecRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecInContainerSpecRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExecInContainerSpecRequest proto.InternalMessageInfo

func (m *ExecInContainerSpecRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ExecInContainerSpecRequest) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}

func (m *ExecInContainerSpecRequest) GetSpec() string {
	if m != nil {
		return m.Spec
	}
	return ""
}

func (m *ExecInContainerSpecRequest) GetContainerName() string {
	if m != nil {
		return m.ContainerName
	}
	return ""
}

func (m *ExecInContainerSpecRequest) GetCmd() string {
	if m != nil {
		return m.Cmd
	}
	return ""
}

type ExecInContainerSpecResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecInContainerSpecResponse) Reset()         { *m = ExecInContainerSpecResponse{} }
func (m *ExecInContainerSpecResponse) String() string { return proto.CompactTextString(m) }
func (*ExecInContainerSpecResponse) ProtoMessage()    {}
func (*ExecInContainerSpecResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1a676bd7648f983, []int{7}
}

func (m *ExecInContainerSpecResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecInContainerSpecResponse.Unmarshal(m, b)
}
func (m *ExecInContainerSpecResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecInContainerSpecResponse.Marshal(b, m, deterministic)
}
func (m *ExecInContainerSpecResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecInContainerSpecResponse.Merge(m, src)
}
func (m *ExecInContainerSpecResponse) XXX_Size() int {
	return xxx_messageInfo_ExecInContainerSpecResponse.Size(m)
}
func (m *ExecInContainerSpecResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecInContainerSpecResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExecInContainerSpecResponse proto.InternalMessageInfo

type LoadImageRequest struct {
	URL                  string   `protobuf:"bytes,1,opt,name=URL,proto3" json:"URL,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoadImageRequest) Reset()         { *m = LoadImageRequest{} }
func (m *LoadImageRequest) String() string { return proto.CompactTextString(m) }
func (*LoadImageRequest) ProtoMessage()    {}
func (*LoadImageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1a676bd7648f983, []int{8}
}

func (m *LoadImageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadImageRequest.Unmarshal(m, b)
}
func (m *LoadImageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadImageRequest.Marshal(b, m, deterministic)
}
func (m *LoadImageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadImageRequest.Merge(m, src)
}
func (m *LoadImageRequest) XXX_Size() int {
	return xxx_messageInfo_LoadImageRequest.Size(m)
}
func (m *LoadImageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadImageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoadImageRequest proto.InternalMessageInfo

func (m *LoadImageRequest) GetURL() string {
	if m != nil {
		return m.URL
	}
	return ""
}

type LoadImageResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoadImageResponse) Reset()         { *m = LoadImageResponse{} }
func (m *LoadImageResponse) String() string { return proto.CompactTextString(m) }
func (*LoadImageResponse) ProtoMessage()    {}
func (*LoadImageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1a676bd7648f983, []int{9}
}

func (m *LoadImageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadImageResponse.Unmarshal(m, b)
}
func (m *LoadImageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadImageResponse.Marshal(b, m, deterministic)
}
func (m *LoadImageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadImageResponse.Merge(m, src)
}
func (m *LoadImageResponse) XXX_Size() int {
	return xxx_messageInfo_LoadImageResponse.Size(m)
}
func (m *LoadImageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadImageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoadImageResponse proto.InternalMessageInfo

type UnloadImageRequest struct {
	Tag                  string   `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnloadImageRequest) Reset()         { *m = UnloadImageRequest{} }
func (m *UnloadImageRequest) String() string { return proto.CompactTextString(m) }
func (*UnloadImageRequest) ProtoMessage()    {}
func (*UnloadImageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1a676bd7648f983, []int{10}
}

func (m *UnloadImageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnloadImageRequest.Unmarshal(m, b)
}
func (m *UnloadImageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnloadImageRequest.Marshal(b, m, deterministic)
}
func (m *UnloadImageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnloadImageRequest.Merge(m, src)
}
func (m *UnloadImageRequest) XXX_Size() int {
	return xxx_messageInfo_UnloadImageRequest.Size(m)
}
func (m *UnloadImageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnloadImageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnloadImageRequest proto.InternalMessageInfo

func (m *UnloadImageRequest) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

type UnloadImageResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnloadImageResponse) Reset()         { *m = UnloadImageResponse{} }
func (m *UnloadImageResponse) String() string { return proto.CompactTextString(m) }
func (*UnloadImageResponse) ProtoMessage()    {}
func (*UnloadImageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1a676bd7648f983, []int{11}
}

func (m *UnloadImageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnloadImageResponse.Unmarshal(m, b)
}
func (m *UnloadImageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnloadImageResponse.Marshal(b, m, deterministic)
}
func (m *UnloadImageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnloadImageResponse.Merge(m, src)
}
func (m *UnloadImageResponse) XXX_Size() int {
	return xxx_messageInfo_UnloadImageResponse.Size(m)
}
func (m *UnloadImageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UnloadImageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UnloadImageResponse proto.InternalMessageInfo

type MountDriveResponse struct {
	Errors               []string `protobuf:"bytes,1,rep,name=errors,proto3" json:"errors,omitempty"`
	IsSuccessful         bool     `protobuf:"varint,2,opt,name=is_successful,json=isSuccessful,proto3" json:"is_successful,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MountDriveResponse) Reset()         { *m = MountDriveResponse{} }
func (m *MountDriveResponse) String() string { return proto.CompactTextString(m) }
func (*MountDriveResponse) ProtoMessage()    {}
func (*MountDriveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1a676bd7648f983, []int{12}
}

func (m *MountDriveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MountDriveResponse.Unmarshal(m, b)
}
func (m *MountDriveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MountDriveResponse.Marshal(b, m, deterministic)
}
func (m *MountDriveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MountDriveResponse.Merge(m, src)
}
func (m *MountDriveResponse) XXX_Size() int {
	return xxx_messageInfo_MountDriveResponse.Size(m)
}
func (m *MountDriveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MountDriveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MountDriveResponse proto.InternalMessageInfo

func (m *MountDriveResponse) GetErrors() []string {
	if m != nil {
		return m.Errors
	}
	return nil
}

func (m *MountDriveResponse) GetIsSuccessful() bool {
	if m != nil {
		return m.IsSuccessful
	}
	return false
}

type MountDriveRequest struct {
	DeviceFile           string   `protobuf:"bytes,1,opt,name=device_file,json=deviceFile,proto3" json:"device_file,omitempty"`
	MountPoint           string   `protobuf:"bytes,2,opt,name=mount_point,json=mountPoint,proto3" json:"mount_point,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MountDriveRequest) Reset()         { *m = MountDriveRequest{} }
func (m *MountDriveRequest) String() string { return proto.CompactTextString(m) }
func (*MountDriveRequest) ProtoMessage()    {}
func (*MountDriveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1a676bd7648f983, []int{13}
}

func (m *MountDriveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MountDriveRequest.Unmarshal(m, b)
}
func (m *MountDriveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MountDriveRequest.Marshal(b, m, deterministic)
}
func (m *MountDriveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MountDriveRequest.Merge(m, src)
}
func (m *MountDriveRequest) XXX_Size() int {
	return xxx_messageInfo_MountDriveRequest.Size(m)
}
func (m *MountDriveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MountDriveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MountDriveRequest proto.InternalMessageInfo

func (m *MountDriveRequest) GetDeviceFile() string {
	if m != nil {
		return m.DeviceFile
	}
	return ""
}

func (m *MountDriveRequest) GetMountPoint() string {
	if m != nil {
		return m.MountPoint
	}
	return ""
}

type UnmountDriveRequest struct {
	DeviceFile           string   `protobuf:"bytes,1,opt,name=device_file,json=deviceFile,proto3" json:"device_file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnmountDriveRequest) Reset()         { *m = UnmountDriveRequest{} }
func (m *UnmountDriveRequest) String() string { return proto.CompactTextString(m) }
func (*UnmountDriveRequest) ProtoMessage()    {}
func (*UnmountDriveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1a676bd7648f983, []int{14}
}

func (m *UnmountDriveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnmountDriveRequest.Unmarshal(m, b)
}
func (m *UnmountDriveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnmountDriveRequest.Marshal(b, m, deterministic)
}
func (m *UnmountDriveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnmountDriveRequest.Merge(m, src)
}
func (m *UnmountDriveRequest) XXX_Size() int {
	return xxx_messageInfo_UnmountDriveRequest.Size(m)
}
func (m *UnmountDriveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnmountDriveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnmountDriveRequest proto.InternalMessageInfo

func (m *UnmountDriveRequest) GetDeviceFile() string {
	if m != nil {
		return m.DeviceFile
	}
	return ""
}

type UnmountDriveResponse struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	IsSuccessful         bool     `protobuf:"varint,2,opt,name=is_successful,json=isSuccessful,proto3" json:"is_successful,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnmountDriveResponse) Reset()         { *m = UnmountDriveResponse{} }
func (m *UnmountDriveResponse) String() string { return proto.CompactTextString(m) }
func (*UnmountDriveResponse) ProtoMessage()    {}
func (*UnmountDriveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1a676bd7648f983, []int{15}
}

func (m *UnmountDriveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnmountDriveResponse.Unmarshal(m, b)
}
func (m *UnmountDriveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnmountDriveResponse.Marshal(b, m, deterministic)
}
func (m *UnmountDriveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnmountDriveResponse.Merge(m, src)
}
func (m *UnmountDriveResponse) XXX_Size() int {
	return xxx_messageInfo_UnmountDriveResponse.Size(m)
}
func (m *UnmountDriveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UnmountDriveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UnmountDriveResponse proto.InternalMessageInfo

func (m *UnmountDriveResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *UnmountDriveResponse) GetIsSuccessful() bool {
	if m != nil {
		return m.IsSuccessful
	}
	return false
}

type GetDrivesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDrivesRequest) Reset()         { *m = GetDrivesRequest{} }
func (m *GetDrivesRequest) String() string { return proto.CompactTextString(m) }
func (*GetDrivesRequest) ProtoMessage()    {}
func (*GetDrivesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1a676bd7648f983, []int{16}
}

func (m *GetDrivesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDrivesRequest.Unmarshal(m, b)
}
func (m *GetDrivesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDrivesRequest.Marshal(b, m, deterministic)
}
func (m *GetDrivesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDrivesRequest.Merge(m, src)
}
func (m *GetDrivesRequest) XXX_Size() int {
	return xxx_messageInfo_GetDrivesRequest.Size(m)
}
func (m *GetDrivesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDrivesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDrivesRequest proto.InternalMessageInfo

type GetDrivesResponse struct {
	Drives               []*Drive `protobuf:"bytes,1,rep,name=drives,proto3" json:"drives,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDrivesResponse) Reset()         { *m = GetDrivesResponse{} }
func (m *GetDrivesResponse) String() string { return proto.CompactTextString(m) }
func (*GetDrivesResponse) ProtoMessage()    {}
func (*GetDrivesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1a676bd7648f983, []int{17}
}

func (m *GetDrivesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDrivesResponse.Unmarshal(m, b)
}
func (m *GetDrivesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDrivesResponse.Marshal(b, m, deterministic)
}
func (m *GetDrivesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDrivesResponse.Merge(m, src)
}
func (m *GetDrivesResponse) XXX_Size() int {
	return xxx_messageInfo_GetDrivesResponse.Size(m)
}
func (m *GetDrivesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDrivesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDrivesResponse proto.InternalMessageInfo

func (m *GetDrivesResponse) GetDrives() []*Drive {
	if m != nil {
		return m.Drives
	}
	return nil
}

type Drive struct {
	Name                 string       `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DeviceFile           string       `protobuf:"bytes,2,opt,name=device_file,json=deviceFile,proto3" json:"device_file,omitempty"`
	SizeBytes            uint64       `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	IsRemovable          bool         `protobuf:"varint,4,opt,name=is_removable,json=isRemovable,proto3" json:"is_removable,omitempty"`
	Type                 string       `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	SerialNumber         string       `protobuf:"bytes,6,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	StorageController    string       `protobuf:"bytes,7,opt,name=storage_controller,json=storageController,proto3" json:"storage_controller,omitempty"`
	Partitions           []*Partition `protobuf:"bytes,8,rep,name=partitions,proto3" json:"partitions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Drive) Reset()         { *m = Drive{} }
func (m *Drive) String() string { return proto.CompactTextString(m) }
func (*Drive) ProtoMessage()    {}
func (*Drive) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1a676bd7648f983, []int{18}
}

func (m *Drive) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Drive.Unmarshal(m, b)
}
func (m *Drive) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Drive.Marshal(b, m, deterministic)
}
func (m *Drive) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Drive.Merge(m, src)
}
func (m *Drive) XXX_Size() int {
	return xxx_messageInfo_Drive.Size(m)
}
func (m *Drive) XXX_DiscardUnknown() {
	xxx_messageInfo_Drive.DiscardUnknown(m)
}

var xxx_messageInfo_Drive proto.InternalMessageInfo

func (m *Drive) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Drive) GetDeviceFile() string {
	if m != nil {
		return m.DeviceFile
	}
	return ""
}

func (m *Drive) GetSizeBytes() uint64 {
	if m != nil {
		return m.SizeBytes
	}
	return 0
}

func (m *Drive) GetIsRemovable() bool {
	if m != nil {
		return m.IsRemovable
	}
	return false
}

func (m *Drive) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Drive) GetSerialNumber() string {
	if m != nil {
		return m.SerialNumber
	}
	return ""
}

func (m *Drive) GetStorageController() string {
	if m != nil {
		return m.StorageController
	}
	return ""
}

func (m *Drive) GetPartitions() []*Partition {
	if m != nil {
		return m.Partitions
	}
	return nil
}

type Partition struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DeviceFile           string   `protobuf:"bytes,2,opt,name=device_file,json=deviceFile,proto3" json:"device_file,omitempty"`
	SizeBytes            uint64   `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	AvailableBytes       uint64   `protobuf:"varint,4,opt,name=available_bytes,json=availableBytes,proto3" json:"available_bytes,omitempty"`
	Filesystem           string   `protobuf:"bytes,5,opt,name=filesystem,proto3" json:"filesystem,omitempty"`
	MountPoint           string   `protobuf:"bytes,6,opt,name=mount_point,json=mountPoint,proto3" json:"mount_point,omitempty"`
	Label                string   `protobuf:"bytes,7,opt,name=label,proto3" json:"label,omitempty"`
	IsReadOnly           bool     `protobuf:"varint,8,opt,name=is_read_only,json=isReadOnly,proto3" json:"is_read_only,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Partition) Reset()         { *m = Partition{} }
func (m *Partition) String() string { return proto.CompactTextString(m) }
func (*Partition) ProtoMessage()    {}
func (*Partition) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1a676bd7648f983, []int{19}
}

func (m *Partition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Partition.Unmarshal(m, b)
}
func (m *Partition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Partition.Marshal(b, m, deterministic)
}
func (m *Partition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Partition.Merge(m, src)
}
func (m *Partition) XXX_Size() int {
	return xxx_messageInfo_Partition.Size(m)
}
func (m *Partition) XXX_DiscardUnknown() {
	xxx_messageInfo_Partition.DiscardUnknown(m)
}

var xxx_messageInfo_Partition proto.InternalMessageInfo

func (m *Partition) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Partition) GetDeviceFile() string {
	if m != nil {
		return m.DeviceFile
	}
	return ""
}

func (m *Partition) GetSizeBytes() uint64 {
	if m != nil {
		return m.SizeBytes
	}
	return 0
}

func (m *Partition) GetAvailableBytes() uint64 {
	if m != nil {
		return m.AvailableBytes
	}
	return 0
}

func (m *Partition) GetFilesystem() string {
	if m != nil {
		return m.Filesystem
	}
	return ""
}

func (m *Partition) GetMountPoint() string {
	if m != nil {
		return m.MountPoint
	}
	return ""
}

func (m *Partition) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *Partition) GetIsReadOnly() bool {
	if m != nil {
		return m.IsReadOnly
	}
	return false
}

type Result struct {
	ExitCode             int32    `protobuf:"varint,1,opt,name=exitCode,proto3" json:"exitCode,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1a676bd7648f983, []int{20}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetExitCode() int32 {
	if m != nil {
		return m.ExitCode
	}
	return 0
}

func (m *Result) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Command struct {
	Command              string   `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Command) Reset()         { *m = Command{} }
func (m *Command) String() string { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()    {}
func (*Command) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1a676bd7648f983, []int{21}
}

func (m *Command) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Command.Unmarshal(m, b)
}
func (m *Command) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Command.Marshal(b, m, deterministic)
}
func (m *Command) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Command.Merge(m, src)
}
func (m *Command) XXX_Size() int {
	return xxx_messageInfo_Command.Size(m)
}
func (m *Command) XXX_DiscardUnknown() {
	xxx_messageInfo_Command.DiscardUnknown(m)
}

var xxx_messageInfo_Command proto.InternalMessageInfo

func (m *Command) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func init() {
	proto.RegisterType((*RunContainerRequest)(nil), "proto.RunContainerRequest")
	proto.RegisterType((*RunContainerResponse)(nil), "proto.RunContainerResponse")
	proto.RegisterType((*KillContainerRequest)(nil), "proto.KillContainerRequest")
	proto.RegisterType((*KillContainerResponse)(nil), "proto.KillContainerResponse")
	proto.RegisterType((*ContainerSpecRequest)(nil), "proto.ContainerSpecRequest")
	proto.RegisterType((*ContainerSpecResponse)(nil), "proto.ContainerSpecResponse")
	proto.RegisterType((*ExecInContainerSpecRequest)(nil), "proto.ExecInContainerSpecRequest")
	proto.RegisterType((*ExecInContainerSpecResponse)(nil), "proto.ExecInContainerSpecResponse")
	proto.RegisterType((*LoadImageRequest)(nil), "proto.LoadImageRequest")
	proto.RegisterType((*LoadImageResponse)(nil), "proto.LoadImageResponse")
	proto.RegisterType((*UnloadImageRequest)(nil), "proto.UnloadImageRequest")
	proto.RegisterType((*UnloadImageResponse)(nil), "proto.UnloadImageResponse")
	proto.RegisterType((*MountDriveResponse)(nil), "proto.MountDriveResponse")
	proto.RegisterType((*MountDriveRequest)(nil), "proto.MountDriveRequest")
	proto.RegisterType((*UnmountDriveRequest)(nil), "proto.UnmountDriveRequest")
	proto.RegisterType((*UnmountDriveResponse)(nil), "proto.UnmountDriveResponse")
	proto.RegisterType((*GetDrivesRequest)(nil), "proto.GetDrivesRequest")
	proto.RegisterType((*GetDrivesResponse)(nil), "proto.GetDrivesResponse")
	proto.RegisterType((*Drive)(nil), "proto.Drive")
	proto.RegisterType((*Partition)(nil), "proto.Partition")
	proto.RegisterType((*Result)(nil), "proto.Result")
	proto.RegisterType((*Command)(nil), "proto.Command")
}

func init() {
	proto.RegisterFile("hurra_agent.proto", fileDescriptor_d1a676bd7648f983)
}

var fileDescriptor_d1a676bd7648f983 = []byte{
	// 932 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xb4, 0x56, 0xdf, 0x6f, 0x1c, 0x35,
	0x10, 0xbe, 0x24, 0xf7, 0x23, 0x99, 0xcb, 0x85, 0x3b, 0xdf, 0xb5, 0xdd, 0x6e, 0x29, 0xb4, 0x6e,
	0xf9, 0x21, 0x24, 0x22, 0x54, 0x24, 0x24, 0x5e, 0x10, 0xf4, 0xa0, 0x10, 0x91, 0xb6, 0x61, 0x43,
	0x24, 0xc4, 0x03, 0x2b, 0x67, 0xcf, 0x0d, 0x96, 0x76, 0xd7, 0x8b, 0xed, 0x8d, 0x12, 0xde, 0x78,
	0xe3, 0x3f, 0x80, 0x37, 0xfe, 0x55, 0x6c, 0xaf, 0xd7, 0xdd, 0xec, 0x2d, 0x55, 0x91, 0x9a, 0xa7,
	0xb5, 0xbf, 0xf9, 0xfc, 0x79, 0x3c, 0xf6, 0xcc, 0x2c, 0xcc, 0x7e, 0x2d, 0x85, 0x20, 0x31, 0x39,
	0xa3, 0xb9, 0xda, 0x2f, 0x04, 0x57, 0x1c, 0x0d, 0xec, 0x07, 0xff, 0xb3, 0x01, 0xf3, 0xa8, 0xcc,
	0x97, 0x3c, 0x57, 0x84, 0xe5, 0x54, 0x44, 0xf4, 0xb7, 0x92, 0x4a, 0x85, 0x10, 0xf4, 0x73, 0x92,
	0xd1, 0x60, 0xe3, 0xde, 0xc6, 0x87, 0x3b, 0x91, 0x1d, 0xa3, 0x05, 0x0c, 0x58, 0xa6, 0x35, 0x82,
	0x4d, 0x0b, 0x56, 0x13, 0xb4, 0x0f, 0xf3, 0x82, 0x0b, 0x15, 0x67, 0xa4, 0x28, 0x58, 0x7e, 0x16,
	0x4b, 0x5e, 0x8a, 0x84, 0x06, 0x5b, 0x9a, 0x33, 0x89, 0x66, 0xc6, 0xf4, 0xb4, 0xb2, 0x1c, 0x5b,
	0xc3, 0x1a, 0x5f, 0x11, 0x71, 0x46, 0x55, 0xd0, 0x5f, 0xe3, 0xff, 0x68, 0x0d, 0xf8, 0x26, 0x2c,
	0xae, 0x3a, 0x28, 0x0b, 0x9e, 0x4b, 0x8a, 0x3f, 0x82, 0xc5, 0xf7, 0x2c, 0x4d, 0x5f, 0xc7, 0x73,
	0x7c, 0x0b, 0x6e, 0xb4, 0xb8, 0x4e, 0xe4, 0x27, 0x58, 0x78, 0xf0, 0xb8, 0xa0, 0xc9, 0xab, 0x8e,
	0x1f, 0xc0, 0x28, 0xd1, 0x5c, 0x7a, 0xa1, 0x5c, 0x00, 0xea, 0xa9, 0x61, 0x4b, 0xbd, 0xd8, 0x9e,
	0x59, 0xb3, 0xcd, 0xd8, 0x6c, 0xd9, 0x52, 0x76, 0x5b, 0xfe, 0xb5, 0x01, 0xe1, 0x37, 0x17, 0x34,
	0x39, 0xc8, 0xaf, 0x67, 0x67, 0xf4, 0x1e, 0xec, 0x25, 0xb5, 0x72, 0x6c, 0xb5, 0xfa, 0xd6, 0x3a,
	0xf1, 0xe8, 0x33, 0x23, 0x3a, 0x85, 0xad, 0x24, 0x5b, 0x05, 0x03, 0x6b, 0x33, 0x43, 0x7c, 0x17,
	0xee, 0x74, 0x3a, 0xe6, 0x1c, 0x7f, 0x08, 0xd3, 0x43, 0x4e, 0x56, 0x07, 0xe6, 0xd6, 0x6b, 0x6f,
	0xb5, 0xc8, 0x49, 0x74, 0xe8, 0x9c, 0x35, 0x43, 0x3c, 0x87, 0x59, 0x83, 0xe5, 0x96, 0xbe, 0x0f,
	0xe8, 0x24, 0x4f, 0x3b, 0x16, 0x2b, 0x72, 0x56, 0x2f, 0xd6, 0x43, 0x7c, 0x03, 0xe6, 0x57, 0x78,
	0x6e, 0xf9, 0x0f, 0x80, 0x9e, 0xf2, 0x32, 0x57, 0x5f, 0x0b, 0x76, 0xee, 0x51, 0x74, 0x13, 0x86,
	0x54, 0x08, 0x2e, 0xa4, 0x56, 0xd8, 0xd2, 0x0a, 0x6e, 0x86, 0x1e, 0xc0, 0x84, 0xc9, 0x58, 0x96,
	0x49, 0x42, 0xa5, 0x7c, 0x51, 0xa6, 0x36, 0x66, 0xdb, 0xd1, 0x2e, 0x93, 0xc7, 0x1e, 0xc3, 0x27,
	0x30, 0x6b, 0x4a, 0x56, 0x0e, 0xbd, 0x0b, 0xe3, 0x15, 0x3d, 0x67, 0x09, 0x8d, 0x5f, 0xb0, 0xb4,
	0xbe, 0x02, 0xa8, 0xa0, 0x27, 0x1a, 0x31, 0x84, 0xcc, 0xac, 0x8a, 0x0b, 0xce, 0xf2, 0xfa, 0x32,
	0xc0, 0x42, 0x47, 0x06, 0xc1, 0x9f, 0x99, 0x03, 0x64, 0xff, 0x5b, 0x58, 0x9f, 0x70, 0x71, 0x75,
	0x9d, 0x3b, 0xa3, 0x4e, 0x39, 0x7b, 0x2a, 0xb7, 0xa4, 0x9a, 0xbc, 0xde, 0x09, 0x11, 0x4c, 0xbf,
	0xa5, 0x95, 0x9c, 0x74, 0x7e, 0xe0, 0xcf, 0x61, 0xd6, 0xc0, 0xdc, 0x1e, 0x0f, 0x61, 0xb8, 0xb2,
	0x88, 0x8d, 0xe3, 0xf8, 0xd1, 0x6e, 0x55, 0x21, 0xf6, 0x2b, 0x4f, 0x9c, 0x0d, 0xff, 0xbd, 0x09,
	0x03, 0x8b, 0x74, 0xbe, 0xd0, 0xd6, 0x01, 0x37, 0xd7, 0x22, 0x77, 0x17, 0x40, 0xb2, 0xdf, 0x69,
	0x7c, 0x7a, 0xa9, 0xf4, 0x46, 0xe6, 0xb9, 0xf6, 0xa3, 0x1d, 0x83, 0x3c, 0x36, 0x00, 0xba, 0x0f,
	0xda, 0xf9, 0x58, 0xd0, 0x8c, 0x9f, 0x93, 0xd3, 0xb4, 0x7a, 0xb1, 0xdb, 0xd1, 0x98, 0x69, 0x2f,
	0x1d, 0x64, 0xb6, 0x55, 0x97, 0x05, 0x75, 0x0f, 0xd6, 0x8e, 0x4d, 0x20, 0x24, 0x15, 0x8c, 0xa4,
	0x71, 0x5e, 0x66, 0xa7, 0x54, 0x04, 0x43, 0x6b, 0xdc, 0xad, 0xc0, 0x67, 0x16, 0x43, 0x1f, 0x03,
	0x92, 0x8a, 0x0b, 0xfd, 0xa0, 0x62, 0x93, 0x01, 0x82, 0xa7, 0xa9, 0x66, 0x8e, 0x2c, 0x73, 0xe6,
	0x2c, 0x4b, 0x6f, 0x40, 0x9f, 0x00, 0x14, 0x44, 0x28, 0xa6, 0x98, 0x8e, 0x4e, 0xb0, 0x6d, 0x43,
	0x32, 0x75, 0x21, 0x39, 0xaa, 0x0d, 0x51, 0x83, 0x83, 0xff, 0xd8, 0x84, 0x1d, 0x6f, 0xb9, 0x96,
	0xf0, 0x7c, 0x00, 0x6f, 0x91, 0x73, 0xc2, 0x52, 0x13, 0x08, 0xc7, 0xe9, 0x5b, 0xce, 0x9e, 0x87,
	0x2b, 0xe2, 0x3b, 0x00, 0x66, 0x07, 0x79, 0x29, 0x15, 0xcd, 0x5c, 0xa8, 0x1a, 0x48, 0xfb, 0x01,
	0x0f, 0xdb, 0x0f, 0xd8, 0x3c, 0x38, 0x2d, 0x47, 0x53, 0x17, 0x9f, 0x6a, 0x82, 0xee, 0xb9, 0xeb,
	0x21, 0xab, 0x98, 0xe7, 0xe9, 0xa5, 0x8e, 0x8a, 0xb9, 0x1e, 0x30, 0xd7, 0x43, 0x56, 0xcf, 0x35,
	0x82, 0xbf, 0x80, 0xa1, 0x7e, 0x50, 0x65, 0xaa, 0x50, 0x08, 0xdb, 0xf4, 0x82, 0xa9, 0x25, 0x5f,
	0x55, 0x31, 0x18, 0x44, 0x7e, 0x6e, 0x0a, 0x59, 0xa6, 0x9f, 0xe7, 0xcb, 0x1e, 0x52, 0x4f, 0xf1,
	0x03, 0x18, 0x2d, 0x79, 0x96, 0x91, 0x7c, 0x55, 0x55, 0x3b, 0x3b, 0x74, 0x31, 0xac, 0xa7, 0x8f,
	0xfe, 0x1c, 0x01, 0x7c, 0x67, 0x3a, 0xd9, 0x57, 0xa6, 0x91, 0xa1, 0x25, 0xc0, 0xcb, 0x1c, 0x46,
	0x81, 0xbb, 0xa3, 0xb5, 0xb4, 0x0e, 0x6f, 0x77, 0x58, 0x5c, 0x65, 0xe9, 0xa1, 0x03, 0xd8, 0x6d,
	0x66, 0x1e, 0x0a, 0x1d, 0xb9, 0x23, 0x8d, 0xc3, 0x3b, 0x9d, 0x36, 0x2f, 0xf5, 0x25, 0xec, 0xf8,
	0xec, 0x42, 0xb7, 0x1c, 0xb7, 0x9d, 0x83, 0x61, 0xb0, 0x6e, 0x68, 0x2a, 0xf8, 0xe2, 0xe9, 0x15,
	0xda, 0x45, 0xd7, 0x2b, 0xac, 0xd7, 0xd9, 0x1e, 0x7a, 0x02, 0xe3, 0x46, 0x05, 0x45, 0xb7, 0xbd,
	0xc7, 0xed, 0xea, 0x1b, 0x86, 0x5d, 0xa6, 0x66, 0x58, 0x9a, 0x5d, 0xd7, 0x87, 0xa5, 0xe3, 0x5f,
	0xc1, 0x87, 0xa5, 0xb3, 0x4d, 0xf7, 0xd0, 0x21, 0x4c, 0xae, 0x34, 0x5f, 0x54, 0xf3, 0xbb, 0xda,
	0x77, 0xf8, 0x76, 0xb7, 0xd1, 0xab, 0x3d, 0x87, 0x69, 0x73, 0x1f, 0xd3, 0xa1, 0xbc, 0x60, 0x57,
	0x43, 0xf5, 0x82, 0xdd, 0x4d, 0xad, 0x87, 0x8e, 0x60, 0x76, 0xac, 0x78, 0xf1, 0x06, 0x15, 0x23,
	0xfd, 0x4b, 0x65, 0xca, 0x16, 0x7d, 0x83, 0x9a, 0xbf, 0xc0, 0xbc, 0xa3, 0x37, 0xa3, 0xfb, 0x6e,
	0xd9, 0x7f, 0xff, 0x50, 0x84, 0xf8, 0x55, 0x14, 0xaf, 0xbf, 0x0f, 0x63, 0x43, 0xa8, 0x73, 0x70,
	0xcf, 0xbb, 0x63, 0xe7, 0xe1, 0xa4, 0xbe, 0x62, 0x9b, 0xe3, 0xb8, 0xf7, 0x78, 0xf4, 0x73, 0xf5,
	0x03, 0x79, 0x3a, 0xb4, 0x9f, 0x4f, 0xff, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xb5, 0x45, 0x85, 0x7b,
	0x63, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// HurraAgentClient is the client API for HurraAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HurraAgentClient interface {
	MountDrive(ctx context.Context, in *MountDriveRequest, opts ...grpc.CallOption) (*MountDriveResponse, error)
	UnmountDrive(ctx context.Context, in *UnmountDriveRequest, opts ...grpc.CallOption) (*UnmountDriveResponse, error)
	GetDrives(ctx context.Context, in *GetDrivesRequest, opts ...grpc.CallOption) (*GetDrivesResponse, error)
	LoadImage(ctx context.Context, in *LoadImageRequest, opts ...grpc.CallOption) (*LoadImageResponse, error)
	UnloadImage(ctx context.Context, in *UnloadImageRequest, opts ...grpc.CallOption) (*UnloadImageResponse, error)
	RunContainer(ctx context.Context, in *RunContainerRequest, opts ...grpc.CallOption) (*RunContainerResponse, error)
	KillContainer(ctx context.Context, in *KillContainerRequest, opts ...grpc.CallOption) (*KillContainerResponse, error)
	RunContainerSpec(ctx context.Context, in *ContainerSpecRequest, opts ...grpc.CallOption) (*ContainerSpecResponse, error)
	StopContainerSpec(ctx context.Context, in *ContainerSpecRequest, opts ...grpc.CallOption) (*ContainerSpecResponse, error)
	RemoveContainerSpec(ctx context.Context, in *ContainerSpecRequest, opts ...grpc.CallOption) (*ContainerSpecResponse, error)
	ExecInContainerSpec(ctx context.Context, in *ExecInContainerSpecRequest, opts ...grpc.CallOption) (*ExecInContainerSpecResponse, error)
	ExecCommand(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Result, error)
}

type hurraAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewHurraAgentClient(cc grpc.ClientConnInterface) HurraAgentClient {
	return &hurraAgentClient{cc}
}

func (c *hurraAgentClient) MountDrive(ctx context.Context, in *MountDriveRequest, opts ...grpc.CallOption) (*MountDriveResponse, error) {
	out := new(MountDriveResponse)
	err := c.cc.Invoke(ctx, "/proto.HurraAgent/MountDrive", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hurraAgentClient) UnmountDrive(ctx context.Context, in *UnmountDriveRequest, opts ...grpc.CallOption) (*UnmountDriveResponse, error) {
	out := new(UnmountDriveResponse)
	err := c.cc.Invoke(ctx, "/proto.HurraAgent/UnmountDrive", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hurraAgentClient) GetDrives(ctx context.Context, in *GetDrivesRequest, opts ...grpc.CallOption) (*GetDrivesResponse, error) {
	out := new(GetDrivesResponse)
	err := c.cc.Invoke(ctx, "/proto.HurraAgent/GetDrives", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hurraAgentClient) LoadImage(ctx context.Context, in *LoadImageRequest, opts ...grpc.CallOption) (*LoadImageResponse, error) {
	out := new(LoadImageResponse)
	err := c.cc.Invoke(ctx, "/proto.HurraAgent/LoadImage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hurraAgentClient) UnloadImage(ctx context.Context, in *UnloadImageRequest, opts ...grpc.CallOption) (*UnloadImageResponse, error) {
	out := new(UnloadImageResponse)
	err := c.cc.Invoke(ctx, "/proto.HurraAgent/UnloadImage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hurraAgentClient) RunContainer(ctx context.Context, in *RunContainerRequest, opts ...grpc.CallOption) (*RunContainerResponse, error) {
	out := new(RunContainerResponse)
	err := c.cc.Invoke(ctx, "/proto.HurraAgent/RunContainer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hurraAgentClient) KillContainer(ctx context.Context, in *KillContainerRequest, opts ...grpc.CallOption) (*KillContainerResponse, error) {
	out := new(KillContainerResponse)
	err := c.cc.Invoke(ctx, "/proto.HurraAgent/KillContainer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hurraAgentClient) RunContainerSpec(ctx context.Context, in *ContainerSpecRequest, opts ...grpc.CallOption) (*ContainerSpecResponse, error) {
	out := new(ContainerSpecResponse)
	err := c.cc.Invoke(ctx, "/proto.HurraAgent/RunContainerSpec", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hurraAgentClient) StopContainerSpec(ctx context.Context, in *ContainerSpecRequest, opts ...grpc.CallOption) (*ContainerSpecResponse, error) {
	out := new(ContainerSpecResponse)
	err := c.cc.Invoke(ctx, "/proto.HurraAgent/StopContainerSpec", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hurraAgentClient) RemoveContainerSpec(ctx context.Context, in *ContainerSpecRequest, opts ...grpc.CallOption) (*ContainerSpecResponse, error) {
	out := new(ContainerSpecResponse)
	err := c.cc.Invoke(ctx, "/proto.HurraAgent/RemoveContainerSpec", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hurraAgentClient) ExecInContainerSpec(ctx context.Context, in *ExecInContainerSpecRequest, opts ...grpc.CallOption) (*ExecInContainerSpecResponse, error) {
	out := new(ExecInContainerSpecResponse)
	err := c.cc.Invoke(ctx, "/proto.HurraAgent/ExecInContainerSpec", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hurraAgentClient) ExecCommand(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/proto.HurraAgent/ExecCommand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HurraAgentServer is the server API for HurraAgent service.
type HurraAgentServer interface {
	MountDrive(context.Context, *MountDriveRequest) (*MountDriveResponse, error)
	UnmountDrive(context.Context, *UnmountDriveRequest) (*UnmountDriveResponse, error)
	GetDrives(context.Context, *GetDrivesRequest) (*GetDrivesResponse, error)
	LoadImage(context.Context, *LoadImageRequest) (*LoadImageResponse, error)
	UnloadImage(context.Context, *UnloadImageRequest) (*UnloadImageResponse, error)
	RunContainer(context.Context, *RunContainerRequest) (*RunContainerResponse, error)
	KillContainer(context.Context, *KillContainerRequest) (*KillContainerResponse, error)
	RunContainerSpec(context.Context, *ContainerSpecRequest) (*ContainerSpecResponse, error)
	StopContainerSpec(context.Context, *ContainerSpecRequest) (*ContainerSpecResponse, error)
	RemoveContainerSpec(context.Context, *ContainerSpecRequest) (*ContainerSpecResponse, error)
	ExecInContainerSpec(context.Context, *ExecInContainerSpecRequest) (*ExecInContainerSpecResponse, error)
	ExecCommand(context.Context, *Command) (*Result, error)
}

// UnimplementedHurraAgentServer can be embedded to have forward compatible implementations.
type UnimplementedHurraAgentServer struct {
}

func (*UnimplementedHurraAgentServer) MountDrive(ctx context.Context, req *MountDriveRequest) (*MountDriveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MountDrive not implemented")
}
func (*UnimplementedHurraAgentServer) UnmountDrive(ctx context.Context, req *UnmountDriveRequest) (*UnmountDriveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnmountDrive not implemented")
}
func (*UnimplementedHurraAgentServer) GetDrives(ctx context.Context, req *GetDrivesRequest) (*GetDrivesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDrives not implemented")
}
func (*UnimplementedHurraAgentServer) LoadImage(ctx context.Context, req *LoadImageRequest) (*LoadImageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadImage not implemented")
}
func (*UnimplementedHurraAgentServer) UnloadImage(ctx context.Context, req *UnloadImageRequest) (*UnloadImageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnloadImage not implemented")
}
func (*UnimplementedHurraAgentServer) RunContainer(ctx context.Context, req *RunContainerRequest) (*RunContainerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunContainer not implemented")
}
func (*UnimplementedHurraAgentServer) KillContainer(ctx context.Context, req *KillContainerRequest) (*KillContainerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KillContainer not implemented")
}
func (*UnimplementedHurraAgentServer) RunContainerSpec(ctx context.Context, req *ContainerSpecRequest) (*ContainerSpecResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunContainerSpec not implemented")
}
func (*UnimplementedHurraAgentServer) StopContainerSpec(ctx context.Context, req *ContainerSpecRequest) (*ContainerSpecResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopContainerSpec not implemented")
}
func (*UnimplementedHurraAgentServer) RemoveContainerSpec(ctx context.Context, req *ContainerSpecRequest) (*ContainerSpecResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveContainerSpec not implemented")
}
func (*UnimplementedHurraAgentServer) ExecInContainerSpec(ctx context.Context, req *ExecInContainerSpecRequest) (*ExecInContainerSpecResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecInContainerSpec not implemented")
}
func (*UnimplementedHurraAgentServer) ExecCommand(ctx context.Context, req *Command) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecCommand not implemented")
}

func RegisterHurraAgentServer(s *grpc.Server, srv HurraAgentServer) {
	s.RegisterService(&_HurraAgent_serviceDesc, srv)
}

func _HurraAgent_MountDrive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MountDriveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HurraAgentServer).MountDrive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.HurraAgent/MountDrive",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HurraAgentServer).MountDrive(ctx, req.(*MountDriveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HurraAgent_UnmountDrive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnmountDriveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HurraAgentServer).UnmountDrive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.HurraAgent/UnmountDrive",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HurraAgentServer).UnmountDrive(ctx, req.(*UnmountDriveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HurraAgent_GetDrives_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDrivesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HurraAgentServer).GetDrives(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.HurraAgent/GetDrives",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HurraAgentServer).GetDrives(ctx, req.(*GetDrivesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HurraAgent_LoadImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HurraAgentServer).LoadImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.HurraAgent/LoadImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HurraAgentServer).LoadImage(ctx, req.(*LoadImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HurraAgent_UnloadImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnloadImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HurraAgentServer).UnloadImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.HurraAgent/UnloadImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HurraAgentServer).UnloadImage(ctx, req.(*UnloadImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HurraAgent_RunContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunContainerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HurraAgentServer).RunContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.HurraAgent/RunContainer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HurraAgentServer).RunContainer(ctx, req.(*RunContainerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HurraAgent_KillContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KillContainerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HurraAgentServer).KillContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.HurraAgent/KillContainer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HurraAgentServer).KillContainer(ctx, req.(*KillContainerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HurraAgent_RunContainerSpec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainerSpecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HurraAgentServer).RunContainerSpec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.HurraAgent/RunContainerSpec",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HurraAgentServer).RunContainerSpec(ctx, req.(*ContainerSpecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HurraAgent_StopContainerSpec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainerSpecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HurraAgentServer).StopContainerSpec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.HurraAgent/StopContainerSpec",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HurraAgentServer).StopContainerSpec(ctx, req.(*ContainerSpecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HurraAgent_RemoveContainerSpec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainerSpecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HurraAgentServer).RemoveContainerSpec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.HurraAgent/RemoveContainerSpec",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HurraAgentServer).RemoveContainerSpec(ctx, req.(*ContainerSpecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HurraAgent_ExecInContainerSpec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecInContainerSpecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HurraAgentServer).ExecInContainerSpec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.HurraAgent/ExecInContainerSpec",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HurraAgentServer).ExecInContainerSpec(ctx, req.(*ExecInContainerSpecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HurraAgent_ExecCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Command)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HurraAgentServer).ExecCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.HurraAgent/ExecCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HurraAgentServer).ExecCommand(ctx, req.(*Command))
	}
	return interceptor(ctx, in, info, handler)
}

var _HurraAgent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.HurraAgent",
	HandlerType: (*HurraAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MountDrive",
			Handler:    _HurraAgent_MountDrive_Handler,
		},
		{
			MethodName: "UnmountDrive",
			Handler:    _HurraAgent_UnmountDrive_Handler,
		},
		{
			MethodName: "GetDrives",
			Handler:    _HurraAgent_GetDrives_Handler,
		},
		{
			MethodName: "LoadImage",
			Handler:    _HurraAgent_LoadImage_Handler,
		},
		{
			MethodName: "UnloadImage",
			Handler:    _HurraAgent_UnloadImage_Handler,
		},
		{
			MethodName: "RunContainer",
			Handler:    _HurraAgent_RunContainer_Handler,
		},
		{
			MethodName: "KillContainer",
			Handler:    _HurraAgent_KillContainer_Handler,
		},
		{
			MethodName: "RunContainerSpec",
			Handler:    _HurraAgent_RunContainerSpec_Handler,
		},
		{
			MethodName: "StopContainerSpec",
			Handler:    _HurraAgent_StopContainerSpec_Handler,
		},
		{
			MethodName: "RemoveContainerSpec",
			Handler:    _HurraAgent_RemoveContainerSpec_Handler,
		},
		{
			MethodName: "ExecInContainerSpec",
			Handler:    _HurraAgent_ExecInContainerSpec_Handler,
		},
		{
			MethodName: "ExecCommand",
			Handler:    _HurraAgent_ExecCommand_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hurra_agent.proto",
}
