// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hurra_agent.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ContainersRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Context              string   `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	Spec                 string   `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContainersRequest) Reset()         { *m = ContainersRequest{} }
func (m *ContainersRequest) String() string { return proto.CompactTextString(m) }
func (*ContainersRequest) ProtoMessage()    {}
func (*ContainersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1a676bd7648f983, []int{0}
}

func (m *ContainersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContainersRequest.Unmarshal(m, b)
}
func (m *ContainersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContainersRequest.Marshal(b, m, deterministic)
}
func (m *ContainersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContainersRequest.Merge(m, src)
}
func (m *ContainersRequest) XXX_Size() int {
	return xxx_messageInfo_ContainersRequest.Size(m)
}
func (m *ContainersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ContainersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ContainersRequest proto.InternalMessageInfo

func (m *ContainersRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ContainersRequest) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}

func (m *ContainersRequest) GetSpec() string {
	if m != nil {
		return m.Spec
	}
	return ""
}

type ContainersResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContainersResponse) Reset()         { *m = ContainersResponse{} }
func (m *ContainersResponse) String() string { return proto.CompactTextString(m) }
func (*ContainersResponse) ProtoMessage()    {}
func (*ContainersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1a676bd7648f983, []int{1}
}

func (m *ContainersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContainersResponse.Unmarshal(m, b)
}
func (m *ContainersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContainersResponse.Marshal(b, m, deterministic)
}
func (m *ContainersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContainersResponse.Merge(m, src)
}
func (m *ContainersResponse) XXX_Size() int {
	return xxx_messageInfo_ContainersResponse.Size(m)
}
func (m *ContainersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ContainersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ContainersResponse proto.InternalMessageInfo

type ExecInContainerRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Context              string   `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	Spec                 string   `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"`
	ContainerName        string   `protobuf:"bytes,4,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	Cmd                  string   `protobuf:"bytes,5,opt,name=cmd,proto3" json:"cmd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecInContainerRequest) Reset()         { *m = ExecInContainerRequest{} }
func (m *ExecInContainerRequest) String() string { return proto.CompactTextString(m) }
func (*ExecInContainerRequest) ProtoMessage()    {}
func (*ExecInContainerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1a676bd7648f983, []int{2}
}

func (m *ExecInContainerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecInContainerRequest.Unmarshal(m, b)
}
func (m *ExecInContainerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecInContainerRequest.Marshal(b, m, deterministic)
}
func (m *ExecInContainerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecInContainerRequest.Merge(m, src)
}
func (m *ExecInContainerRequest) XXX_Size() int {
	return xxx_messageInfo_ExecInContainerRequest.Size(m)
}
func (m *ExecInContainerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecInContainerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExecInContainerRequest proto.InternalMessageInfo

func (m *ExecInContainerRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ExecInContainerRequest) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}

func (m *ExecInContainerRequest) GetSpec() string {
	if m != nil {
		return m.Spec
	}
	return ""
}

func (m *ExecInContainerRequest) GetContainerName() string {
	if m != nil {
		return m.ContainerName
	}
	return ""
}

func (m *ExecInContainerRequest) GetCmd() string {
	if m != nil {
		return m.Cmd
	}
	return ""
}

type ExecInContainerResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecInContainerResponse) Reset()         { *m = ExecInContainerResponse{} }
func (m *ExecInContainerResponse) String() string { return proto.CompactTextString(m) }
func (*ExecInContainerResponse) ProtoMessage()    {}
func (*ExecInContainerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1a676bd7648f983, []int{3}
}

func (m *ExecInContainerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecInContainerResponse.Unmarshal(m, b)
}
func (m *ExecInContainerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecInContainerResponse.Marshal(b, m, deterministic)
}
func (m *ExecInContainerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecInContainerResponse.Merge(m, src)
}
func (m *ExecInContainerResponse) XXX_Size() int {
	return xxx_messageInfo_ExecInContainerResponse.Size(m)
}
func (m *ExecInContainerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecInContainerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExecInContainerResponse proto.InternalMessageInfo

type LoadImageRequest struct {
	URL                  string   `protobuf:"bytes,1,opt,name=URL,proto3" json:"URL,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoadImageRequest) Reset()         { *m = LoadImageRequest{} }
func (m *LoadImageRequest) String() string { return proto.CompactTextString(m) }
func (*LoadImageRequest) ProtoMessage()    {}
func (*LoadImageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1a676bd7648f983, []int{4}
}

func (m *LoadImageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadImageRequest.Unmarshal(m, b)
}
func (m *LoadImageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadImageRequest.Marshal(b, m, deterministic)
}
func (m *LoadImageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadImageRequest.Merge(m, src)
}
func (m *LoadImageRequest) XXX_Size() int {
	return xxx_messageInfo_LoadImageRequest.Size(m)
}
func (m *LoadImageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadImageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoadImageRequest proto.InternalMessageInfo

func (m *LoadImageRequest) GetURL() string {
	if m != nil {
		return m.URL
	}
	return ""
}

type LoadImageResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoadImageResponse) Reset()         { *m = LoadImageResponse{} }
func (m *LoadImageResponse) String() string { return proto.CompactTextString(m) }
func (*LoadImageResponse) ProtoMessage()    {}
func (*LoadImageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1a676bd7648f983, []int{5}
}

func (m *LoadImageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadImageResponse.Unmarshal(m, b)
}
func (m *LoadImageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadImageResponse.Marshal(b, m, deterministic)
}
func (m *LoadImageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadImageResponse.Merge(m, src)
}
func (m *LoadImageResponse) XXX_Size() int {
	return xxx_messageInfo_LoadImageResponse.Size(m)
}
func (m *LoadImageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadImageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoadImageResponse proto.InternalMessageInfo

type UnloadImageRequest struct {
	Tag                  string   `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnloadImageRequest) Reset()         { *m = UnloadImageRequest{} }
func (m *UnloadImageRequest) String() string { return proto.CompactTextString(m) }
func (*UnloadImageRequest) ProtoMessage()    {}
func (*UnloadImageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1a676bd7648f983, []int{6}
}

func (m *UnloadImageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnloadImageRequest.Unmarshal(m, b)
}
func (m *UnloadImageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnloadImageRequest.Marshal(b, m, deterministic)
}
func (m *UnloadImageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnloadImageRequest.Merge(m, src)
}
func (m *UnloadImageRequest) XXX_Size() int {
	return xxx_messageInfo_UnloadImageRequest.Size(m)
}
func (m *UnloadImageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnloadImageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnloadImageRequest proto.InternalMessageInfo

func (m *UnloadImageRequest) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

type UnloadImageResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnloadImageResponse) Reset()         { *m = UnloadImageResponse{} }
func (m *UnloadImageResponse) String() string { return proto.CompactTextString(m) }
func (*UnloadImageResponse) ProtoMessage()    {}
func (*UnloadImageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1a676bd7648f983, []int{7}
}

func (m *UnloadImageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnloadImageResponse.Unmarshal(m, b)
}
func (m *UnloadImageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnloadImageResponse.Marshal(b, m, deterministic)
}
func (m *UnloadImageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnloadImageResponse.Merge(m, src)
}
func (m *UnloadImageResponse) XXX_Size() int {
	return xxx_messageInfo_UnloadImageResponse.Size(m)
}
func (m *UnloadImageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UnloadImageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UnloadImageResponse proto.InternalMessageInfo

type MountDriveResponse struct {
	Errors               []string `protobuf:"bytes,1,rep,name=errors,proto3" json:"errors,omitempty"`
	IsSuccessful         bool     `protobuf:"varint,2,opt,name=is_successful,json=isSuccessful,proto3" json:"is_successful,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MountDriveResponse) Reset()         { *m = MountDriveResponse{} }
func (m *MountDriveResponse) String() string { return proto.CompactTextString(m) }
func (*MountDriveResponse) ProtoMessage()    {}
func (*MountDriveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1a676bd7648f983, []int{8}
}

func (m *MountDriveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MountDriveResponse.Unmarshal(m, b)
}
func (m *MountDriveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MountDriveResponse.Marshal(b, m, deterministic)
}
func (m *MountDriveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MountDriveResponse.Merge(m, src)
}
func (m *MountDriveResponse) XXX_Size() int {
	return xxx_messageInfo_MountDriveResponse.Size(m)
}
func (m *MountDriveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MountDriveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MountDriveResponse proto.InternalMessageInfo

func (m *MountDriveResponse) GetErrors() []string {
	if m != nil {
		return m.Errors
	}
	return nil
}

func (m *MountDriveResponse) GetIsSuccessful() bool {
	if m != nil {
		return m.IsSuccessful
	}
	return false
}

type MountDriveRequest struct {
	DeviceFile           string   `protobuf:"bytes,1,opt,name=device_file,json=deviceFile,proto3" json:"device_file,omitempty"`
	MountPoint           string   `protobuf:"bytes,2,opt,name=mount_point,json=mountPoint,proto3" json:"mount_point,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MountDriveRequest) Reset()         { *m = MountDriveRequest{} }
func (m *MountDriveRequest) String() string { return proto.CompactTextString(m) }
func (*MountDriveRequest) ProtoMessage()    {}
func (*MountDriveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1a676bd7648f983, []int{9}
}

func (m *MountDriveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MountDriveRequest.Unmarshal(m, b)
}
func (m *MountDriveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MountDriveRequest.Marshal(b, m, deterministic)
}
func (m *MountDriveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MountDriveRequest.Merge(m, src)
}
func (m *MountDriveRequest) XXX_Size() int {
	return xxx_messageInfo_MountDriveRequest.Size(m)
}
func (m *MountDriveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MountDriveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MountDriveRequest proto.InternalMessageInfo

func (m *MountDriveRequest) GetDeviceFile() string {
	if m != nil {
		return m.DeviceFile
	}
	return ""
}

func (m *MountDriveRequest) GetMountPoint() string {
	if m != nil {
		return m.MountPoint
	}
	return ""
}

type UnmountDriveRequest struct {
	DeviceFile           string   `protobuf:"bytes,1,opt,name=device_file,json=deviceFile,proto3" json:"device_file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnmountDriveRequest) Reset()         { *m = UnmountDriveRequest{} }
func (m *UnmountDriveRequest) String() string { return proto.CompactTextString(m) }
func (*UnmountDriveRequest) ProtoMessage()    {}
func (*UnmountDriveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1a676bd7648f983, []int{10}
}

func (m *UnmountDriveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnmountDriveRequest.Unmarshal(m, b)
}
func (m *UnmountDriveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnmountDriveRequest.Marshal(b, m, deterministic)
}
func (m *UnmountDriveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnmountDriveRequest.Merge(m, src)
}
func (m *UnmountDriveRequest) XXX_Size() int {
	return xxx_messageInfo_UnmountDriveRequest.Size(m)
}
func (m *UnmountDriveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnmountDriveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnmountDriveRequest proto.InternalMessageInfo

func (m *UnmountDriveRequest) GetDeviceFile() string {
	if m != nil {
		return m.DeviceFile
	}
	return ""
}

type UnmountDriveResponse struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	IsSuccessful         bool     `protobuf:"varint,2,opt,name=is_successful,json=isSuccessful,proto3" json:"is_successful,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnmountDriveResponse) Reset()         { *m = UnmountDriveResponse{} }
func (m *UnmountDriveResponse) String() string { return proto.CompactTextString(m) }
func (*UnmountDriveResponse) ProtoMessage()    {}
func (*UnmountDriveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1a676bd7648f983, []int{11}
}

func (m *UnmountDriveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnmountDriveResponse.Unmarshal(m, b)
}
func (m *UnmountDriveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnmountDriveResponse.Marshal(b, m, deterministic)
}
func (m *UnmountDriveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnmountDriveResponse.Merge(m, src)
}
func (m *UnmountDriveResponse) XXX_Size() int {
	return xxx_messageInfo_UnmountDriveResponse.Size(m)
}
func (m *UnmountDriveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UnmountDriveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UnmountDriveResponse proto.InternalMessageInfo

func (m *UnmountDriveResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *UnmountDriveResponse) GetIsSuccessful() bool {
	if m != nil {
		return m.IsSuccessful
	}
	return false
}

type GetDrivesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDrivesRequest) Reset()         { *m = GetDrivesRequest{} }
func (m *GetDrivesRequest) String() string { return proto.CompactTextString(m) }
func (*GetDrivesRequest) ProtoMessage()    {}
func (*GetDrivesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1a676bd7648f983, []int{12}
}

func (m *GetDrivesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDrivesRequest.Unmarshal(m, b)
}
func (m *GetDrivesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDrivesRequest.Marshal(b, m, deterministic)
}
func (m *GetDrivesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDrivesRequest.Merge(m, src)
}
func (m *GetDrivesRequest) XXX_Size() int {
	return xxx_messageInfo_GetDrivesRequest.Size(m)
}
func (m *GetDrivesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDrivesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDrivesRequest proto.InternalMessageInfo

type GetDrivesResponse struct {
	Drives               []*Drive `protobuf:"bytes,1,rep,name=drives,proto3" json:"drives,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDrivesResponse) Reset()         { *m = GetDrivesResponse{} }
func (m *GetDrivesResponse) String() string { return proto.CompactTextString(m) }
func (*GetDrivesResponse) ProtoMessage()    {}
func (*GetDrivesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1a676bd7648f983, []int{13}
}

func (m *GetDrivesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDrivesResponse.Unmarshal(m, b)
}
func (m *GetDrivesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDrivesResponse.Marshal(b, m, deterministic)
}
func (m *GetDrivesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDrivesResponse.Merge(m, src)
}
func (m *GetDrivesResponse) XXX_Size() int {
	return xxx_messageInfo_GetDrivesResponse.Size(m)
}
func (m *GetDrivesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDrivesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDrivesResponse proto.InternalMessageInfo

func (m *GetDrivesResponse) GetDrives() []*Drive {
	if m != nil {
		return m.Drives
	}
	return nil
}

type Drive struct {
	Name                 string       `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DeviceFile           string       `protobuf:"bytes,2,opt,name=device_file,json=deviceFile,proto3" json:"device_file,omitempty"`
	SizeBytes            uint64       `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	IsRemovable          bool         `protobuf:"varint,4,opt,name=is_removable,json=isRemovable,proto3" json:"is_removable,omitempty"`
	Type                 string       `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	SerialNumber         string       `protobuf:"bytes,6,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	StorageController    string       `protobuf:"bytes,7,opt,name=storage_controller,json=storageController,proto3" json:"storage_controller,omitempty"`
	Partitions           []*Partition `protobuf:"bytes,8,rep,name=partitions,proto3" json:"partitions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Drive) Reset()         { *m = Drive{} }
func (m *Drive) String() string { return proto.CompactTextString(m) }
func (*Drive) ProtoMessage()    {}
func (*Drive) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1a676bd7648f983, []int{14}
}

func (m *Drive) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Drive.Unmarshal(m, b)
}
func (m *Drive) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Drive.Marshal(b, m, deterministic)
}
func (m *Drive) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Drive.Merge(m, src)
}
func (m *Drive) XXX_Size() int {
	return xxx_messageInfo_Drive.Size(m)
}
func (m *Drive) XXX_DiscardUnknown() {
	xxx_messageInfo_Drive.DiscardUnknown(m)
}

var xxx_messageInfo_Drive proto.InternalMessageInfo

func (m *Drive) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Drive) GetDeviceFile() string {
	if m != nil {
		return m.DeviceFile
	}
	return ""
}

func (m *Drive) GetSizeBytes() uint64 {
	if m != nil {
		return m.SizeBytes
	}
	return 0
}

func (m *Drive) GetIsRemovable() bool {
	if m != nil {
		return m.IsRemovable
	}
	return false
}

func (m *Drive) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Drive) GetSerialNumber() string {
	if m != nil {
		return m.SerialNumber
	}
	return ""
}

func (m *Drive) GetStorageController() string {
	if m != nil {
		return m.StorageController
	}
	return ""
}

func (m *Drive) GetPartitions() []*Partition {
	if m != nil {
		return m.Partitions
	}
	return nil
}

type Partition struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DeviceFile           string   `protobuf:"bytes,2,opt,name=device_file,json=deviceFile,proto3" json:"device_file,omitempty"`
	SizeBytes            uint64   `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	AvailableBytes       uint64   `protobuf:"varint,4,opt,name=available_bytes,json=availableBytes,proto3" json:"available_bytes,omitempty"`
	Filesystem           string   `protobuf:"bytes,5,opt,name=filesystem,proto3" json:"filesystem,omitempty"`
	MountPoint           string   `protobuf:"bytes,6,opt,name=mount_point,json=mountPoint,proto3" json:"mount_point,omitempty"`
	Label                string   `protobuf:"bytes,7,opt,name=label,proto3" json:"label,omitempty"`
	IsReadOnly           bool     `protobuf:"varint,8,opt,name=is_read_only,json=isReadOnly,proto3" json:"is_read_only,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Partition) Reset()         { *m = Partition{} }
func (m *Partition) String() string { return proto.CompactTextString(m) }
func (*Partition) ProtoMessage()    {}
func (*Partition) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1a676bd7648f983, []int{15}
}

func (m *Partition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Partition.Unmarshal(m, b)
}
func (m *Partition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Partition.Marshal(b, m, deterministic)
}
func (m *Partition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Partition.Merge(m, src)
}
func (m *Partition) XXX_Size() int {
	return xxx_messageInfo_Partition.Size(m)
}
func (m *Partition) XXX_DiscardUnknown() {
	xxx_messageInfo_Partition.DiscardUnknown(m)
}

var xxx_messageInfo_Partition proto.InternalMessageInfo

func (m *Partition) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Partition) GetDeviceFile() string {
	if m != nil {
		return m.DeviceFile
	}
	return ""
}

func (m *Partition) GetSizeBytes() uint64 {
	if m != nil {
		return m.SizeBytes
	}
	return 0
}

func (m *Partition) GetAvailableBytes() uint64 {
	if m != nil {
		return m.AvailableBytes
	}
	return 0
}

func (m *Partition) GetFilesystem() string {
	if m != nil {
		return m.Filesystem
	}
	return ""
}

func (m *Partition) GetMountPoint() string {
	if m != nil {
		return m.MountPoint
	}
	return ""
}

func (m *Partition) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *Partition) GetIsReadOnly() bool {
	if m != nil {
		return m.IsReadOnly
	}
	return false
}

type Result struct {
	ExitCode             int32    `protobuf:"varint,1,opt,name=exitCode,proto3" json:"exitCode,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1a676bd7648f983, []int{16}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetExitCode() int32 {
	if m != nil {
		return m.ExitCode
	}
	return 0
}

func (m *Result) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Command struct {
	Command              string   `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Command) Reset()         { *m = Command{} }
func (m *Command) String() string { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()    {}
func (*Command) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1a676bd7648f983, []int{17}
}

func (m *Command) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Command.Unmarshal(m, b)
}
func (m *Command) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Command.Marshal(b, m, deterministic)
}
func (m *Command) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Command.Merge(m, src)
}
func (m *Command) XXX_Size() int {
	return xxx_messageInfo_Command.Size(m)
}
func (m *Command) XXX_DiscardUnknown() {
	xxx_messageInfo_Command.DiscardUnknown(m)
}

var xxx_messageInfo_Command proto.InternalMessageInfo

func (m *Command) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func init() {
	proto.RegisterType((*ContainersRequest)(nil), "proto.ContainersRequest")
	proto.RegisterType((*ContainersResponse)(nil), "proto.ContainersResponse")
	proto.RegisterType((*ExecInContainerRequest)(nil), "proto.ExecInContainerRequest")
	proto.RegisterType((*ExecInContainerResponse)(nil), "proto.ExecInContainerResponse")
	proto.RegisterType((*LoadImageRequest)(nil), "proto.LoadImageRequest")
	proto.RegisterType((*LoadImageResponse)(nil), "proto.LoadImageResponse")
	proto.RegisterType((*UnloadImageRequest)(nil), "proto.UnloadImageRequest")
	proto.RegisterType((*UnloadImageResponse)(nil), "proto.UnloadImageResponse")
	proto.RegisterType((*MountDriveResponse)(nil), "proto.MountDriveResponse")
	proto.RegisterType((*MountDriveRequest)(nil), "proto.MountDriveRequest")
	proto.RegisterType((*UnmountDriveRequest)(nil), "proto.UnmountDriveRequest")
	proto.RegisterType((*UnmountDriveResponse)(nil), "proto.UnmountDriveResponse")
	proto.RegisterType((*GetDrivesRequest)(nil), "proto.GetDrivesRequest")
	proto.RegisterType((*GetDrivesResponse)(nil), "proto.GetDrivesResponse")
	proto.RegisterType((*Drive)(nil), "proto.Drive")
	proto.RegisterType((*Partition)(nil), "proto.Partition")
	proto.RegisterType((*Result)(nil), "proto.Result")
	proto.RegisterType((*Command)(nil), "proto.Command")
}

func init() {
	proto.RegisterFile("hurra_agent.proto", fileDescriptor_d1a676bd7648f983)
}

var fileDescriptor_d1a676bd7648f983 = []byte{
	// 811 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xb4, 0x56, 0x5b, 0x4f, 0xdb, 0x48,
	0x14, 0x0e, 0x21, 0xd7, 0x93, 0x0b, 0xc9, 0xc0, 0x82, 0xf1, 0x0a, 0x96, 0x35, 0xec, 0xe5, 0x65,
	0xd1, 0x8a, 0x95, 0x56, 0xea, 0x4b, 0xd5, 0x92, 0x16, 0x1a, 0x89, 0x52, 0x6a, 0xc4, 0x4b, 0x5f,
	0x2c, 0xc7, 0x1e, 0xa8, 0x25, 0x5f, 0x52, 0xcf, 0x38, 0x22, 0x7d, 0xeb, 0x6f, 0xe8, 0x4b, 0x7f,
	0x52, 0x7f, 0x56, 0xe7, 0xe6, 0xc1, 0x24, 0xae, 0xd4, 0x8a, 0xf6, 0x29, 0x73, 0xbe, 0x73, 0xe6,
	0x9b, 0x33, 0xdf, 0x9c, 0x73, 0x1c, 0x18, 0xbe, 0xcd, 0xd2, 0xd4, 0x75, 0xdc, 0x1b, 0x1c, 0xd3,
	0xc3, 0x69, 0x9a, 0xd0, 0x04, 0xd5, 0xc5, 0x8f, 0x75, 0x05, 0xc3, 0x51, 0x12, 0x53, 0x37, 0x88,
	0x71, 0x4a, 0x6c, 0xfc, 0x2e, 0xc3, 0x84, 0x22, 0x04, 0xb5, 0xd8, 0x8d, 0xb0, 0xb1, 0xb2, 0xb7,
	0xf2, 0x77, 0xdb, 0x16, 0x6b, 0x64, 0x40, 0xd3, 0x63, 0x81, 0xf8, 0x96, 0x1a, 0x55, 0x01, 0xe7,
	0x26, 0x8f, 0x26, 0x53, 0xec, 0x19, 0xab, 0x32, 0x9a, 0xaf, 0xad, 0x0d, 0x40, 0x45, 0x5a, 0x32,
	0x4d, 0x62, 0x82, 0xad, 0x8f, 0x2b, 0xb0, 0xf9, 0xfc, 0x16, 0x7b, 0xe3, 0x58, 0x3b, 0x7f, 0xd8,
	0x91, 0xe8, 0x0f, 0xe8, 0x7b, 0x39, 0xab, 0x23, 0xb8, 0x6a, 0xc2, 0xdb, 0xd3, 0xe8, 0x39, 0x27,
	0x1d, 0xc0, 0xaa, 0x17, 0xf9, 0x46, 0x5d, 0xf8, 0xf8, 0xd2, 0xda, 0x86, 0xad, 0xa5, 0xa4, 0x54,
	0xc2, 0x07, 0x30, 0x38, 0x4b, 0x5c, 0x7f, 0x1c, 0x31, 0xe5, 0xf2, 0x4c, 0x19, 0xc1, 0x95, 0x7d,
	0xa6, 0x12, 0xe5, 0x4b, 0x6b, 0x1d, 0x86, 0x85, 0x28, 0xb5, 0xf5, 0x4f, 0x40, 0x57, 0x71, 0x58,
	0xb2, 0x99, 0xba, 0x37, 0xf9, 0x66, 0xb6, 0xb4, 0x7e, 0x81, 0xf5, 0x7b, 0x71, 0x6a, 0xfb, 0x6b,
	0x40, 0x2f, 0x93, 0x2c, 0xa6, 0xcf, 0xd2, 0x60, 0xa6, 0x51, 0xb4, 0x09, 0x0d, 0x9c, 0xa6, 0x49,
	0x4a, 0x18, 0xc3, 0x2a, 0x63, 0x50, 0x16, 0xda, 0x87, 0x5e, 0x40, 0x1c, 0x92, 0x79, 0x1e, 0x26,
	0xe4, 0x3a, 0x0b, 0x85, 0x5e, 0x2d, 0xbb, 0x1b, 0x90, 0x4b, 0x8d, 0xf1, 0xa7, 0x2e, 0x52, 0xca,
	0x84, 0x7e, 0x83, 0x8e, 0x8f, 0x67, 0x81, 0x87, 0x9d, 0xeb, 0x20, 0xcc, 0xe5, 0x07, 0x09, 0x9d,
	0x30, 0x84, 0x07, 0x44, 0x7c, 0x97, 0x33, 0x4d, 0x82, 0x38, 0x7f, 0x08, 0x10, 0xd0, 0x05, 0x47,
	0xac, 0xff, 0xf9, 0x05, 0xa2, 0xef, 0x26, 0x66, 0x37, 0xdc, 0xb8, 0xbf, 0x4f, 0xdd, 0x71, 0x03,
	0xea, 0xe2, 0x56, 0x6a, 0x8b, 0x34, 0xbe, 0xed, 0x86, 0x08, 0x06, 0xa7, 0x58, 0xd2, 0xe5, 0xb5,
	0x6c, 0x3d, 0x82, 0x61, 0x01, 0x53, 0x67, 0x1c, 0x40, 0xc3, 0x17, 0x88, 0xd0, 0xb1, 0x73, 0xd4,
	0x95, 0x4d, 0x71, 0x28, 0x33, 0x51, 0x3e, 0xeb, 0x53, 0x15, 0xea, 0x02, 0x29, 0xad, 0xce, 0x85,
	0x0b, 0x56, 0x97, 0x94, 0xdb, 0x01, 0x20, 0xc1, 0x7b, 0xec, 0x4c, 0xe6, 0x94, 0x1d, 0xc4, 0x4b,
	0xb5, 0x66, 0xb7, 0x39, 0x72, 0xcc, 0x01, 0xf4, 0x3b, 0xb0, 0xe4, 0x9d, 0x14, 0x47, 0xc9, 0xcc,
	0x9d, 0x84, 0xb2, 0x5a, 0x5b, 0x76, 0x27, 0x60, 0x59, 0x2a, 0x88, 0x1f, 0x4b, 0xe7, 0x53, 0xac,
	0x8a, 0x55, 0xac, 0xb9, 0x10, 0x04, 0xa7, 0x81, 0x1b, 0x3a, 0x71, 0x16, 0x4d, 0x70, 0x6a, 0x34,
	0x84, 0xb3, 0x2b, 0xc1, 0x73, 0x81, 0xa1, 0x7f, 0x00, 0x11, 0x9a, 0xa4, 0xac, 0xa0, 0x1c, 0x5e,
	0xfd, 0x69, 0x12, 0x86, 0x2c, 0xb2, 0x29, 0x22, 0x87, 0xca, 0x33, 0xd2, 0x0e, 0xf4, 0x2f, 0xc0,
	0xd4, 0x4d, 0x69, 0x40, 0x03, 0xa6, 0x8e, 0xd1, 0x12, 0x92, 0x0c, 0x94, 0x24, 0x17, 0xb9, 0xc3,
	0x2e, 0xc4, 0x58, 0x1f, 0xaa, 0xd0, 0xd6, 0x9e, 0x9f, 0x22, 0xcf, 0x5f, 0xb0, 0xe6, 0xce, 0xdc,
	0x20, 0xe4, 0x42, 0xa8, 0x98, 0x9a, 0x88, 0xe9, 0x6b, 0x58, 0x06, 0xee, 0x02, 0xf0, 0x13, 0xc8,
	0x9c, 0x50, 0x1c, 0x29, 0xa9, 0x0a, 0xc8, 0x62, 0x01, 0x37, 0x16, 0x0b, 0x98, 0x17, 0x1c, 0xa3,
	0xc3, 0xa1, 0xd2, 0x47, 0x1a, 0x68, 0x4f, 0x3d, 0x8f, 0xeb, 0x3b, 0x49, 0x1c, 0xce, 0x99, 0x2a,
	0xfc, 0x79, 0x80, 0x3f, 0x8f, 0xeb, 0xbf, 0x62, 0x88, 0xf5, 0x18, 0x1a, 0xac, 0xa0, 0xb2, 0x90,
	0x22, 0x13, 0x5a, 0xf8, 0x36, 0xa0, 0xa3, 0xc4, 0x97, 0x1a, 0xd4, 0x6d, 0x6d, 0xf3, 0x21, 0x16,
	0xb1, 0xf2, 0x64, 0x82, 0xe7, 0x43, 0x4c, 0x99, 0xd6, 0x3e, 0x34, 0x47, 0x49, 0x14, 0xb9, 0xb1,
	0x2f, 0x27, 0x9d, 0x58, 0x2a, 0x0d, 0x73, 0xf3, 0xe8, 0x73, 0x1d, 0xe0, 0x05, 0x1f, 0xde, 0x4f,
	0xf9, 0xec, 0x46, 0x23, 0x80, 0xbb, 0x1e, 0x46, 0x86, 0x7a, 0xa3, 0xa5, 0xb6, 0x36, 0xb7, 0x4b,
	0x3c, 0x6a, 0xb2, 0x54, 0xd0, 0x18, 0xba, 0xc5, 0xce, 0x43, 0xa6, 0x0a, 0x2e, 0x69, 0x63, 0xf3,
	0xd7, 0x52, 0x9f, 0xa6, 0x7a, 0x02, 0x6d, 0xdd, 0x5d, 0x68, 0x4b, 0xc5, 0x2e, 0xf6, 0xa0, 0x69,
	0x2c, 0x3b, 0x8a, 0x0c, 0x7a, 0x78, 0x6a, 0x86, 0xc5, 0xa1, 0xab, 0x19, 0x96, 0xe7, 0x6c, 0x05,
	0x9d, 0x40, 0xa7, 0x30, 0x41, 0xd1, 0xb6, 0xce, 0x78, 0x71, 0xfa, 0x9a, 0x66, 0x99, 0xab, 0xc0,
	0xd3, 0xb3, 0xb3, 0xbb, 0x8f, 0x00, 0xd1, 0xf2, 0x2e, 0x7d, 0x20, 0xb5, 0xbc, 0x25, 0xdf, 0xb8,
	0x0a, 0x3a, 0x85, 0xfe, 0x25, 0x4d, 0xa6, 0x0f, 0x27, 0x1a, 0xc3, 0x40, 0xcc, 0x02, 0xfc, 0x70,
	0x2a, 0x1b, 0xd6, 0x16, 0xbe, 0x71, 0x68, 0x47, 0xc5, 0x97, 0x7f, 0x90, 0xcd, 0xdd, 0xaf, 0xb9,
	0x35, 0xe7, 0x21, 0x74, 0xb8, 0x33, 0xaf, 0xe1, 0xbe, 0x3e, 0x5f, 0xd8, 0x66, 0x4f, 0xd9, 0xb2,
	0x47, 0xac, 0xca, 0x71, 0xf3, 0x8d, 0xfc, 0xcf, 0x31, 0x69, 0x88, 0x9f, 0xff, 0xbe, 0x04, 0x00,
	0x00, 0xff, 0xff, 0x29, 0xd0, 0xfd, 0x08, 0x96, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// HurraAgentClient is the client API for HurraAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HurraAgentClient interface {
	MountDrive(ctx context.Context, in *MountDriveRequest, opts ...grpc.CallOption) (*MountDriveResponse, error)
	UnmountDrive(ctx context.Context, in *UnmountDriveRequest, opts ...grpc.CallOption) (*UnmountDriveResponse, error)
	GetDrives(ctx context.Context, in *GetDrivesRequest, opts ...grpc.CallOption) (*GetDrivesResponse, error)
	LoadImage(ctx context.Context, in *LoadImageRequest, opts ...grpc.CallOption) (*LoadImageResponse, error)
	UnloadImage(ctx context.Context, in *UnloadImageRequest, opts ...grpc.CallOption) (*UnloadImageResponse, error)
	RunContainers(ctx context.Context, in *ContainersRequest, opts ...grpc.CallOption) (*ContainersResponse, error)
	StopContainers(ctx context.Context, in *ContainersRequest, opts ...grpc.CallOption) (*ContainersResponse, error)
	RemoveContainers(ctx context.Context, in *ContainersRequest, opts ...grpc.CallOption) (*ContainersResponse, error)
	ExecInContainer(ctx context.Context, in *ExecInContainerRequest, opts ...grpc.CallOption) (*ExecInContainerResponse, error)
	ExecCommand(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Result, error)
}

type hurraAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewHurraAgentClient(cc grpc.ClientConnInterface) HurraAgentClient {
	return &hurraAgentClient{cc}
}

func (c *hurraAgentClient) MountDrive(ctx context.Context, in *MountDriveRequest, opts ...grpc.CallOption) (*MountDriveResponse, error) {
	out := new(MountDriveResponse)
	err := c.cc.Invoke(ctx, "/proto.HurraAgent/MountDrive", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hurraAgentClient) UnmountDrive(ctx context.Context, in *UnmountDriveRequest, opts ...grpc.CallOption) (*UnmountDriveResponse, error) {
	out := new(UnmountDriveResponse)
	err := c.cc.Invoke(ctx, "/proto.HurraAgent/UnmountDrive", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hurraAgentClient) GetDrives(ctx context.Context, in *GetDrivesRequest, opts ...grpc.CallOption) (*GetDrivesResponse, error) {
	out := new(GetDrivesResponse)
	err := c.cc.Invoke(ctx, "/proto.HurraAgent/GetDrives", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hurraAgentClient) LoadImage(ctx context.Context, in *LoadImageRequest, opts ...grpc.CallOption) (*LoadImageResponse, error) {
	out := new(LoadImageResponse)
	err := c.cc.Invoke(ctx, "/proto.HurraAgent/LoadImage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hurraAgentClient) UnloadImage(ctx context.Context, in *UnloadImageRequest, opts ...grpc.CallOption) (*UnloadImageResponse, error) {
	out := new(UnloadImageResponse)
	err := c.cc.Invoke(ctx, "/proto.HurraAgent/UnloadImage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hurraAgentClient) RunContainers(ctx context.Context, in *ContainersRequest, opts ...grpc.CallOption) (*ContainersResponse, error) {
	out := new(ContainersResponse)
	err := c.cc.Invoke(ctx, "/proto.HurraAgent/RunContainers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hurraAgentClient) StopContainers(ctx context.Context, in *ContainersRequest, opts ...grpc.CallOption) (*ContainersResponse, error) {
	out := new(ContainersResponse)
	err := c.cc.Invoke(ctx, "/proto.HurraAgent/StopContainers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hurraAgentClient) RemoveContainers(ctx context.Context, in *ContainersRequest, opts ...grpc.CallOption) (*ContainersResponse, error) {
	out := new(ContainersResponse)
	err := c.cc.Invoke(ctx, "/proto.HurraAgent/RemoveContainers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hurraAgentClient) ExecInContainer(ctx context.Context, in *ExecInContainerRequest, opts ...grpc.CallOption) (*ExecInContainerResponse, error) {
	out := new(ExecInContainerResponse)
	err := c.cc.Invoke(ctx, "/proto.HurraAgent/ExecInContainer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hurraAgentClient) ExecCommand(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/proto.HurraAgent/ExecCommand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HurraAgentServer is the server API for HurraAgent service.
type HurraAgentServer interface {
	MountDrive(context.Context, *MountDriveRequest) (*MountDriveResponse, error)
	UnmountDrive(context.Context, *UnmountDriveRequest) (*UnmountDriveResponse, error)
	GetDrives(context.Context, *GetDrivesRequest) (*GetDrivesResponse, error)
	LoadImage(context.Context, *LoadImageRequest) (*LoadImageResponse, error)
	UnloadImage(context.Context, *UnloadImageRequest) (*UnloadImageResponse, error)
	RunContainers(context.Context, *ContainersRequest) (*ContainersResponse, error)
	StopContainers(context.Context, *ContainersRequest) (*ContainersResponse, error)
	RemoveContainers(context.Context, *ContainersRequest) (*ContainersResponse, error)
	ExecInContainer(context.Context, *ExecInContainerRequest) (*ExecInContainerResponse, error)
	ExecCommand(context.Context, *Command) (*Result, error)
}

// UnimplementedHurraAgentServer can be embedded to have forward compatible implementations.
type UnimplementedHurraAgentServer struct {
}

func (*UnimplementedHurraAgentServer) MountDrive(ctx context.Context, req *MountDriveRequest) (*MountDriveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MountDrive not implemented")
}
func (*UnimplementedHurraAgentServer) UnmountDrive(ctx context.Context, req *UnmountDriveRequest) (*UnmountDriveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnmountDrive not implemented")
}
func (*UnimplementedHurraAgentServer) GetDrives(ctx context.Context, req *GetDrivesRequest) (*GetDrivesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDrives not implemented")
}
func (*UnimplementedHurraAgentServer) LoadImage(ctx context.Context, req *LoadImageRequest) (*LoadImageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadImage not implemented")
}
func (*UnimplementedHurraAgentServer) UnloadImage(ctx context.Context, req *UnloadImageRequest) (*UnloadImageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnloadImage not implemented")
}
func (*UnimplementedHurraAgentServer) RunContainers(ctx context.Context, req *ContainersRequest) (*ContainersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunContainers not implemented")
}
func (*UnimplementedHurraAgentServer) StopContainers(ctx context.Context, req *ContainersRequest) (*ContainersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopContainers not implemented")
}
func (*UnimplementedHurraAgentServer) RemoveContainers(ctx context.Context, req *ContainersRequest) (*ContainersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveContainers not implemented")
}
func (*UnimplementedHurraAgentServer) ExecInContainer(ctx context.Context, req *ExecInContainerRequest) (*ExecInContainerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecInContainer not implemented")
}
func (*UnimplementedHurraAgentServer) ExecCommand(ctx context.Context, req *Command) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecCommand not implemented")
}

func RegisterHurraAgentServer(s *grpc.Server, srv HurraAgentServer) {
	s.RegisterService(&_HurraAgent_serviceDesc, srv)
}

func _HurraAgent_MountDrive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MountDriveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HurraAgentServer).MountDrive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.HurraAgent/MountDrive",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HurraAgentServer).MountDrive(ctx, req.(*MountDriveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HurraAgent_UnmountDrive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnmountDriveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HurraAgentServer).UnmountDrive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.HurraAgent/UnmountDrive",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HurraAgentServer).UnmountDrive(ctx, req.(*UnmountDriveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HurraAgent_GetDrives_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDrivesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HurraAgentServer).GetDrives(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.HurraAgent/GetDrives",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HurraAgentServer).GetDrives(ctx, req.(*GetDrivesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HurraAgent_LoadImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HurraAgentServer).LoadImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.HurraAgent/LoadImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HurraAgentServer).LoadImage(ctx, req.(*LoadImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HurraAgent_UnloadImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnloadImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HurraAgentServer).UnloadImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.HurraAgent/UnloadImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HurraAgentServer).UnloadImage(ctx, req.(*UnloadImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HurraAgent_RunContainers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HurraAgentServer).RunContainers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.HurraAgent/RunContainers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HurraAgentServer).RunContainers(ctx, req.(*ContainersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HurraAgent_StopContainers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HurraAgentServer).StopContainers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.HurraAgent/StopContainers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HurraAgentServer).StopContainers(ctx, req.(*ContainersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HurraAgent_RemoveContainers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HurraAgentServer).RemoveContainers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.HurraAgent/RemoveContainers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HurraAgentServer).RemoveContainers(ctx, req.(*ContainersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HurraAgent_ExecInContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecInContainerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HurraAgentServer).ExecInContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.HurraAgent/ExecInContainer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HurraAgentServer).ExecInContainer(ctx, req.(*ExecInContainerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HurraAgent_ExecCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Command)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HurraAgentServer).ExecCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.HurraAgent/ExecCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HurraAgentServer).ExecCommand(ctx, req.(*Command))
	}
	return interceptor(ctx, in, info, handler)
}

var _HurraAgent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.HurraAgent",
	HandlerType: (*HurraAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MountDrive",
			Handler:    _HurraAgent_MountDrive_Handler,
		},
		{
			MethodName: "UnmountDrive",
			Handler:    _HurraAgent_UnmountDrive_Handler,
		},
		{
			MethodName: "GetDrives",
			Handler:    _HurraAgent_GetDrives_Handler,
		},
		{
			MethodName: "LoadImage",
			Handler:    _HurraAgent_LoadImage_Handler,
		},
		{
			MethodName: "UnloadImage",
			Handler:    _HurraAgent_UnloadImage_Handler,
		},
		{
			MethodName: "RunContainers",
			Handler:    _HurraAgent_RunContainers_Handler,
		},
		{
			MethodName: "StopContainers",
			Handler:    _HurraAgent_StopContainers_Handler,
		},
		{
			MethodName: "RemoveContainers",
			Handler:    _HurraAgent_RemoveContainers_Handler,
		},
		{
			MethodName: "ExecInContainer",
			Handler:    _HurraAgent_ExecInContainer_Handler,
		},
		{
			MethodName: "ExecCommand",
			Handler:    _HurraAgent_ExecCommand_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hurra_agent.proto",
}
